=== 1vanC1ndr1c/actor-bio-page/gramatika.dtd
<!ELEMENT podaci (glumac*)>
        <!ELEMENT  glumac (ime, prezime, datum_rodjenja, datum_smrti?, visina?, partner*, zanimanje+, biografija, filmografija, rezidencija*)>

        <!ATTLIST glumac glumacId CDATA #REQUIRED ><!-- CDATA = text that doesn't contain markup, not parsed -->
        <!ATTLIST glumac nacionalnost CDATA #REQUIRED >
        <!ATTLIST glumac glumacSpol (M|F) #REQUIRED >
        <!ATTLIST glumac wikiPageTitle CDATA #REQUIRED >
        <!ATTLIST glumac brojDjece CDATA #IMPLIED>

        <!ELEMENT ime (#PCDATA)>       <!-- PCDATA =  parsed -->
        <!ELEMENT prezime (#PCDATA)>
        <!ELEMENT datum_rodjenja (#PCDATA)>
        <!ELEMENT datum_smrti (#PCDATA)>
        <!ELEMENT visina (#PCDATA)>

        <!ELEMENT partner (partnerIme, partnerPrezime)>
        <!ELEMENT partnerIme (#PCDATA)>
        <!ELEMENT partnerPrezime (#PCDATA)>
        <!ATTLIST partner statusVeze (Rastavljeni|OÅ¾enjeni|Udani|Partneri) #REQUIRED>

        <!ELEMENT zanimanje EMPTY>
        <!ATTLIST zanimanje imeZanimanja CDATA #REQUIRED>

        <!ELEMENT biografija (#PCDATA)>
        <!ELEMENT filmografija (#PCDATA)>
        <!ELEMENT rezidencija (#PCDATA)>

=== 1vanC1ndr1c/actor-bio-page/podaci.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="pretvorba.xsl"?>
<!DOCTYPE podaci SYSTEM "gramatika.dtd">

<podaci>
    <glumac glumacId="1" nacionalnost="US" glumacSpol="M" wikiPageTitle="Jeff Goldblum" brojDjece="2">
        <ime>Jeff</ime>
        <prezime>Goldblum</prezime>
        <datum_rodjenja>October 22, 1952</datum_rodjenja>
        <partner statusVeze="Rastavljeni">
            <partnerIme>Patricia</partnerIme>
            <partnerPrezime>Gaul</partnerPrezime>
        </partner>
        <partner statusVeze="Rastavljeni">
            <partnerIme>Geena</partnerIme>
            <partnerPrezime>Davis</partnerPrezime>
        </partner>
        <partner statusVeze="Oženjeni">
            <partnerIme>Emilie</partnerIme>
            <partnerPrezime>Livingston</partnerPrezime>
        </partner>
        <zanimanje imeZanimanja="Glumac"/>
        <biografija>
            Jeffrey Lynn Goldblum (born October 22, 1952) is an American actor and musician.
            He has starred in some of the highest-grossing films of his era,
            Jurassic Park (1993) and Independence Day (1996), as well as their respective sequels,
            The Lost World: Jurassic Park (1997) and Jurassic World: Fallen Kingdom (2018),
            and Independence Day: Resurgence (2016).
            Goldblum starred in films including Invasion of the Body Snatchers (1978),
            The Big Chill (1983), and Into the Night (1985)
            before coming to the attention of wider audiences
            in David Cronenberg's The Fly (1986) which earned him a Saturn Award for Best Actor.
            His other films include The Adventures of Buckaroo Banzai Across the 8th Dimension (1984),
            The Tall Guy (1989), Deep Cover (1992), Powder (1995),
            The Prince of Egypt (1998), Cats &amp; Dogs (2001), Igby Goes Down (2002),
            The Life Aquatic with Steve Zissou (2004), Adam Resurrected (2008),
            Le Week-End (2013), The Grand Budapest Hotel (2014), and Thor: Ragnarok (2017).
            He also starred in several TV series including the eighth and ninth seasons of
            Law &amp; Order: Criminal Intent as Zack Nichols. For directing the short film Little Surprises,
            he was nominated for the Academy Award for Best Live Action Short Film.
        </biografija>
        <filmografija>Death Wish, Nashville, Annie Hall, The Fly, Jurassic Park, Independence Day, Independence Day 2
        </filmografija>
        <rezidencija>Los Angeles, California, U.S.</rezidencija>
        <rezidencija>New York, New York, U.S.</rezidencija>
    </glumac>


    <glumac glumacId="2" nacionalnost="US" glumacSpol="M" wikiPageTitle="Marlon Brando" brojDjece="11">
        <ime>Marlon</ime>
        <prezime>Brando</prezime>
        <datum_rodjenja>April 3, 1924</datum_rodjenja>
        <datum_smrti>July 1, 2004</datum_smrti>
        <visina>175 cm</visina>
        <partner statusVeze="Rastavljeni">
            <partnerIme>Anna</partnerIme>
            <partnerPrezime>Kashfi</partnerPrezime>
        </partner>
        <partner statusVeze="Rastavljeni">
            <partnerIme>Movita</partnerIme>
            <partnerPrezime>Castaneda</partnerPrezime>
        </partner>
        <partner statusVeze="Rastavljeni">
            <partnerIme>Tarita</partnerIme>
            <partnerPrezime>Teriipaia</partnerPrezime>
        </partner>
        <zanimanje imeZanimanja="Glumac"/>
        <zanimanje imeZanimanja="Redatelj"/>
        <biografija>
            Marlon Brando Jr. (April 3, 1924 – July 1, 2004) was an American actor and film director.
            With a career spanning 60 years,
            he is well-regarded for his cultural influence on 20th-century film.
            Brando's Academy Award-winning performances include that of Terry Malloy in On the Waterfront (1954)
            and Don Vito Corleone in The Godfather (1972). Brando was an activist for many causes,
            notably the civil rights movement and various Native American movements.
            He is credited with helping to popularize the Stanislavski system of acting,
            having studied with Stella Adler in the 1940s.
            He is often regarded as one of the first actors to bring Method Acting to mainstream audiences.
            He initially gained acclaim and an Academy Award nomination for reprising the role of Stanley Kowalski
            in the 1951 film adaptation of Tennessee Williams' play A Streetcar Named Desire,
            a role that he originated successfully on Broadway.
            He received further praise for his performance as Terry Malloy in On the Waterfront,
            and his portrayal of the rebellious motorcycle gang leader Johnny Strabler
            in The Wild One proved to be a lasting image in popular culture.
            Brando received Academy Award nominations for playing Emiliano Zapata in Viva Zapata!;
            Mark Antony in Joseph L. Mankiewicz's 1953 film adaptation of Shakespeare's Julius Caesar;
            and Air Force Major Lloyd Gruver in Sayonara (1957),
            an adaptation of James Michener's 1954 novel.
            Brando was included in a list of Top Ten Money Making Stars three times in the 1950s,
            coming in at number 10 in 1954, number 6 in 1955, and number 4 in 1958.
            The 1960s saw Brando's career take a downturn.
            He directed and starred in the cult western film One-Eyed Jacks,
            a critical and commercial flop, after which he delivered a series of box-office failures,
            beginning with the 1962 film adaptation of the novel Mutiny on the Bounty.
            After 10 years, during which he did not appear in a successful film,
            he won his second Academy Award for playing Vito Corleone in Francis Ford Coppola's The Godfather,
            a role critics consider among his greatest.
            The Godfather was then one of the most commercially successful films of all time.
            With that and his Oscar-nominated performance in Last Tango in Paris,
            Brando re-established himself in the ranks of top box-office stars,
            placing sixth and tenth in the Money Making Stars poll in 1972 and 1973,
            respectively. Brando took a four-year hiatus before appearing in The Missouri Breaks (1976).
            After this, he was content with being a highly paid character actor in cameo roles,
            such as in Superman (1978) and The Formula (1980), before taking a nine-year break from motion pictures.
            According to the Guinness Book of World Records,
            Brando was paid a record $3.7 million ($15 million in inflation-adjusted dollars)
            and 11.75% of the gross profits for 13 days' work on Superman.
            He finished out the 1970s with his controversial performance as Colonel Kurtz in another Coppola film,
            Apocalypse Now, a box-office hit for which he was highly paid and which helped
            finance his career layoff during the 1980s.
            Brando was ranked by the American Film Institute as the fourth-greatest movie star among male movie stars
            whose screen debuts occurred in or before 1950. He was one of six professional actors,
            along with Charlie Chaplin, U.S. President Ronald Reagan, Lucille Ball,
            Frank Sinatra, and Marilyn Monroe,
            named in 1999 by Time magazine as one of its 100 Most Important People of the Century.[7]
        </biografija>
        <filmografija>Godfahter, Last Tango in Paris, Apocalypse Now, Superman, On the Waterfront</filmografija>
    </glumac>


    <glumac glumacId="3" nacionalnost="US" glumacSpol="M" wikiPageTitle="Tom Hanks" brojDjece="4">
        <ime>Tom</ime>
        <prezime>Hanks</prezime>
        <datum_rodjenja>July 9, 1956</datum_rodjenja>
        <partner statusVeze="Rastavljeni">
            <partnerIme>Samantha</partnerIme>
            <partnerPrezime>Lewes</partnerPrezime>
        </partner>
        <partner statusVeze="Oženjeni">
            <partnerIme>Rita</partnerIme>
            <partnerPrezime>Wilson</partnerPrezime>
        </partner>
        <zanimanje imeZanimanja="Glumac"/>
        <zanimanje imeZanimanja="Redatelj"/>
        <biografija>
            Thomas Jeffrey Hanks (born July 9, 1956) is an American actor and filmmaker.
            Hanks is known for his comedic and dramatic roles in such films as Splash (1984),
            Big (1988), Turner &amp; Hooch (1989),
            A League of Their Own (1992),
            Sleepless in Seattle (1993), Apollo 13 (1995),
            You've Got Mail (1998), The Green Mile (1999), Cast Away (2000),
            Road to Perdition (2002), Cloud Atlas (2012), Captain Phillips (2013),
            Saving Mr. Banks (2013), and Sully (2016).
            He has also starred in the Robert Langdon film series,
            and voices Sheriff Woody in the Toy Story film series.
            He is one of the most popular and recognizable film stars worldwide,
            and is widely regarded as an American cultural icon.
            Hanks has collaborated with film director Steven Spielberg on five films to date:
            Saving Private Ryan (1998), Catch Me If You Can (2002), The Terminal (2004), Bridge of Spies (2015),
            and The Post (2017), as well as the 2001 miniseries Band of Brothers,
            which launched Hanks as a successful director, producer, and screenwriter. In 2010,
            Spielberg and Hanks were executive producers on the HBO miniseries The Pacific.
            Hanks' films have grossed more than $4.6 billion at U.S.
            and Canadian box offices and more than $9.2 billion worldwide,
            making him the fourth highest-grossing actor in North America.
            Hanks has been nominated for numerous awards during his career.
